import type Database from 'better-sqlite3';
import type { ProductListFilters } from '@shared/types/catalog';
export interface ProductRow {
    id: number;
    product_code: string | null;
    name: string;
    barcode: string | null;
    category_id: number | null;
    category_name: string | null;
    stock: number;
    stock_min: number;
    brand: string | null;
    size: string | null;
    color: string | null;
    description: string | null;
    cost_price: string;
    price_retail: string;
    price_wholesale: string;
    price_dozen: string;
    plancha_qty: number;
    price_plancha: string;
    cajon_qty: number;
    price_cajon: string;
    image_path: string | null;
    is_active: number;
    created_at: string;
    updated_at: string | null;
}
export declare function listProducts(db: Database.Database, filters: ProductListFilters): ProductRow[];
export declare function getProductById(db: Database.Database, id: number): ProductRow | undefined;
export declare function getProductByBarcodeRow(db: Database.Database, barcode: string): ProductRow | undefined;
export declare function searchProductsPos(db: Database.Database, query: string, limit?: number): ProductRow[];
export declare function getProductByBarcode(db: Database.Database, barcode: string, excludeId?: number): {
    id: number;
} | undefined;
export declare function getProductByCode(db: Database.Database, productCode: string, excludeId?: number): {
    id: number;
} | undefined;
export declare function insertProduct(db: Database.Database, data: {
    productCode: string | null;
    name: string;
    barcode: string | null;
    categoryId: number | null;
    stock: number;
    stockMin: number;
    brand: string | null;
    size: string | null;
    color: string | null;
    description: string | null;
    costPrice: string;
    priceRetail: string;
    priceWholesale: string;
    priceDozen: string;
    planchaQty: number;
    pricePlancha: string;
    cajonQty: number;
    priceCajon: string;
    imagePath: string | null;
    isActive: number;
}): number;
export declare function updateProduct(db: Database.Database, id: number, data: {
    productCode: string | null;
    name: string;
    barcode: string | null;
    categoryId: number | null;
    stockMin: number;
    brand: string | null;
    size: string | null;
    color: string | null;
    description: string | null;
    costPrice: string;
    priceRetail: string;
    priceWholesale: string;
    priceDozen: string;
    planchaQty: number;
    pricePlancha: string;
    cajonQty: number;
    priceCajon: string;
    imagePath: string | null;
    isActive: number;
}): void;
export declare function updateProductStock(db: Database.Database, id: number, stock: number): void;
export declare function updateProductImagePath(db: Database.Database, id: number, imagePath: string | null): void;
export declare function softDeleteProduct(db: Database.Database, id: number): void;
export declare function countSaleItemsForProduct(db: Database.Database, productId: number): number;
export declare function hardDeleteProduct(db: Database.Database, id: number): boolean;
export declare function countLowStockProducts(db: Database.Database): number;
