import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { MoneyDisplay } from '../../components/ui/MoneyDisplay';
export function CashExpectedBreakdown({ session, compact = false }) {
    return (_jsxs("div", { className: [
            'rounded-xl border border-surface-border bg-surface-elevated',
            compact ? 'p-4' : 'p-5'
        ].join(' '), children: [_jsxs("div", { className: "mb-4 flex flex-wrap items-end justify-between gap-3", children: [_jsxs("div", { children: [_jsx("h4", { className: "font-medium", children: "Efectivo esperado en caja" }), _jsx("p", { className: "text-xs text-[rgb(var(--text-muted))]", children: "Cu\u00E1nto deber\u00EDa haber al contar billetes y monedas en el turno" })] }), _jsx(MoneyDisplay, { amount: session.expectedInDrawer, size: "lg", className: "font-semibold" })] }), _jsxs("ul", { className: "space-y-2 text-sm", children: [_jsx(BreakdownLine, { label: "Apertura", amount: session.openingAmount, kind: "add" }), _jsx(BreakdownLine, { label: "Ventas en efectivo", amount: session.totalSalesGross, kind: "add" }), session.totalReturns > 0 && (_jsx(BreakdownLine, { label: "Devoluciones (efectivo devuelto al cliente)", amount: session.totalReturns, kind: "subtract" })), session.creditCashCollected !== 0 && (_jsx(BreakdownLine, { label: "Abonos de fiados (efectivo)", amount: Math.abs(session.creditCashCollected), kind: session.creditCashCollected < 0 ? 'subtract' : 'add' })), session.totalIncome > 0 && (_jsx(BreakdownLine, { label: "Ingresos manuales", amount: session.totalIncome, kind: "add" })), session.totalExpense > 0 && (_jsx(BreakdownLine, { label: "Egresos manuales", amount: session.totalExpense, kind: "subtract" })), _jsxs("li", { className: "flex items-center justify-between border-t border-surface-border pt-3 font-medium", children: [_jsx("span", { children: "= Esperado en caja" }), _jsx(MoneyDisplay, { amount: session.expectedInDrawer, size: "sm" })] })] }), (session.totalYapeGross > 0 || session.totalYape > 0 || session.creditYapeCollected !== 0) && (_jsxs("div", { className: "mt-4 rounded-lg border border-fuchsia-500/25 bg-fuchsia-500/5 px-3 py-2 text-sm", children: [_jsxs("div", { className: "flex items-center justify-between gap-3", children: [_jsx("span", { children: "Ventas Yape (no entran al caj\u00F3n)" }), _jsx(MoneyDisplay, { amount: session.totalYape, size: "sm" })] }), session.creditYapeCollected !== 0 && (_jsxs("div", { className: "mt-1 flex items-center justify-between gap-3 text-xs", children: [_jsx("span", { children: "Abonos fiado por Yape" }), _jsx(MoneyDisplay, { amount: session.creditYapeCollected, size: "sm" })] })), session.totalYapeReturns > 0 && (_jsxs("p", { className: "mt-1 text-xs text-[rgb(var(--text-muted))]", children: ["Devoluciones Yape:", ' ', _jsx(MoneyDisplay, { amount: session.totalYapeReturns, size: "sm", className: "inline" })] }))] })), session.totalReturns > 0 && (_jsx("p", { className: "mt-3 text-xs text-amber-700 dark:text-amber-400", children: "Las devoluciones en efectivo restan del caj\u00F3n porque el dinero sale de la caja al cliente." }))] }));
}
function BreakdownLine({ label, amount, kind }) {
    const sign = kind === 'add' ? '+' : '−';
    const color = kind === 'subtract' ? 'text-amber-600' : 'text-[rgb(var(--text-muted))]';
    return (_jsxs("li", { className: "flex items-start justify-between gap-3", children: [_jsxs("span", { className: color, children: [sign, " ", label] }), _jsx(MoneyDisplay, { amount: amount, size: "sm", className: kind === 'subtract' ? 'text-amber-600' : '' })] }));
}
