import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Badge } from '../../components/ui/Badge';
import { Button } from '../../components/ui/Button';
import { MoneyDisplay } from '../../components/ui/MoneyDisplay';
import { formatDateTime } from '../../lib/datetime';
import { salePaymentLabel } from '@shared/lib/payment';
function statusLabel(status) {
    return status === 'voided' ? 'ANULADA' : 'COMPLETADA';
}
export function SalesListTable({ sales, emptyMessage = 'Sin ventas en este turno', onViewDetail, onVoid, onReturn }) {
    return (_jsx("div", { className: "overflow-hidden rounded-xl border border-surface-border", children: _jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { className: "border-b border-surface-border bg-surface-elevated", children: _jsxs("tr", { className: "text-left", children: [_jsx("th", { className: "px-3 py-2 font-medium", children: "Estado" }), _jsx("th", { className: "px-3 py-2 font-medium", children: "Ticket" }), _jsx("th", { className: "px-3 py-2 font-medium", children: "Pago" }), _jsx("th", { className: "px-3 py-2 font-medium", children: "Fecha" }), _jsx("th", { className: "px-3 py-2 font-medium text-center", children: "\u00CDtems" }), _jsx("th", { className: "px-3 py-2 font-medium text-right", children: "Total / Neto" }), _jsx("th", { className: "px-3 py-2 font-medium text-right", children: "Acciones" })] }) }), _jsx("tbody", { children: sales.length === 0 ? (_jsx("tr", { children: _jsx("td", { colSpan: 7, className: "px-4 py-8 text-center text-[rgb(var(--text-muted))]", children: emptyMessage }) })) : (sales.map((s) => (_jsxs("tr", { className: [
                            'border-b border-surface-border/50',
                            s.status === 'voided' ? 'bg-red-500/5' : 'hover:bg-surface-elevated/40'
                        ].join(' '), children: [_jsx("td", { className: "px-3 py-2", children: _jsx(Badge, { variant: s.status === 'voided' ? 'warning' : 'success', children: statusLabel(s.status) }) }), _jsx("td", { className: "px-3 py-2 font-mono", children: s.ticketNumber }), _jsxs("td", { className: "px-3 py-2", children: [_jsx(Badge, { variant: s.isCredit ? 'warning' : s.paymentMethod === 'yape' ? 'default' : 'muted', children: salePaymentLabel(s) }), s.isCredit && s.creditTo && (_jsx("div", { className: "mt-0.5 max-w-[160px] truncate text-xs text-[rgb(var(--text-muted))]", children: s.creditTo }))] }), _jsx("td", { className: "px-3 py-2 text-[rgb(var(--text-muted))]", children: formatDateTime(s.createdAt) }), _jsx("td", { className: "px-3 py-2 text-center tabular-nums", children: s.itemCount }), _jsx("td", { className: "px-3 py-2 text-right", children: s.status === 'voided' ? (_jsx(MoneyDisplay, { amount: s.total, size: "sm" })) : (_jsxs(_Fragment, { children: [_jsx(MoneyDisplay, { amount: s.netTotal, size: "sm" }), s.returnedTotal > 0 && (_jsxs("div", { className: "text-xs text-[rgb(var(--text-muted))]", children: ["Bruto ", _jsx(MoneyDisplay, { amount: s.total, size: "sm", className: "inline" })] }))] })) }), _jsx("td", { className: "px-3 py-2", children: _jsxs("div", { className: "flex justify-end gap-1", children: [_jsx(Button, { variant: "ghost", type: "button", onClick: () => onViewDetail(s), children: "Ver detalle" }), s.status === 'completed' && onReturn && (_jsx(Button, { variant: "ghost", type: "button", onClick: () => onReturn(s), children: "Devolver" })), s.status === 'completed' && onVoid && (_jsx(Button, { variant: "danger", type: "button", onClick: () => onVoid(s), children: "Anular" }))] }) })] }, s.id)))) })] }) }));
}
